### ISSUE TITLE
Game server has a chance to crash on auto-reload

### ISSUE THREAD

**Issue by SeppMe** [rserbitar/ascifight#4]
The BoardSetup method `_place_bases_and_flags` has a decent chance of crashing with an IndexError due to no legal board positions being available. Normally, this would not be a problem as the game would just restart again. However, if a game client is making queries against the game state during this fail-state, the server itself will crash and be unable to recover, when it tries to access global attributes that no longer exist.

This problem frequently comes up when the server is started using uvicorn's `reload` option, while at the same time changes are made to the code - for example if you are hastily patching bugs on a laptop while some 15 people are waiting for you to get the game running.

**Comment by rserbitar** [comment]
Fixed in some commit I forgot . . . Now works that if there is no legal position it will retry to set all bases again. This still does not fix the situation if there is no legal positions with the current map size or its very improbable.

**Comment by rserbitar** [comment]
Fixed in some commit I forgot . . . Now works that if there is no legal position it will retry to set all bases again. This still does not fix the situation if there is no legal positions with the current map size or its very improbable.

**Comment by rserbitar** [comment]
Fixed in some commit I forgot . . . Now works that if there is no legal position it will retry to set all bases again. This still does not fix the situation if there is no legal positions with the current map size or its very improbable.
